import {KoreaRegionData} from 'src/types/koreaMap';

export const koreaRegionEmpty: KoreaRegionData = {
  uid: '',
  id: '',
  title: '',
  main: '',
  type: 'init',
  background: '#ffffff',
  story: 0,
};

//163
export const koreaMapDataInit: KoreaRegionData[] = [
  {
    uid: '',
    id: 'KR-1',
    title: '서울특별시',
    main: '서울특별시',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-2-1',
    title: '수원시',
    main: '경기도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-2-2',
    title: '성남시',
    main: '경기도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-2-3',
    title: '의정부시',
    main: '경기도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-2-4',
    title: '안양시',
    main: '경기도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-2-5',
    title: '부천시',
    main: '경기도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-2-6',
    title: '광명시',
    main: '경기도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-2-7',
    title: '동두천시',
    main: '경기도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-2-8',
    title: '평택시',
    main: '경기도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-2-9',
    title: '안산시',
    main: '경기도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-2-10',
    title: '고양시',
    main: '경기도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-2-11',
    title: '과천시',
    main: '경기도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-2-12',
    title: '구리시',
    main: '경기도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-2-13',
    title: '남양주시',
    main: '경기도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-2-14',
    title: '오산시',
    main: '경기도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-2-15',
    title: '시흥시',
    main: '경기도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-2-16',
    title: '군포시',
    main: '경기도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-2-17',
    title: '의왕시',
    main: '경기도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-2-18',
    title: '하남시',
    main: '경기도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-2-19',
    title: '용인시',
    main: '경기도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-2-20',
    title: '파주시',
    main: '경기도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-2-21',
    title: '이천시',
    main: '경기도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-2-22',
    title: '안성시',
    main: '경기도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-2-23',
    title: '김포시',
    main: '경기도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-2-24',
    title: '화성시',
    main: '경기도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-2-25',
    title: '광주시',
    main: '경기도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-2-26',
    title: '양주시',
    main: '경기도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-2-27',
    title: '포천시',
    main: '경기도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-2-28',
    title: '여주시',
    main: '경기도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-2-29',
    title: '연천군',
    main: '경기도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-2-30',
    title: '가평군',
    main: '경기도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-2-31',
    title: '양평군',
    main: '경기도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-3',
    title: '인천광역시',
    main: '인천광역시',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-3-9',
    title: '강화군',
    main: '인천광역시',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-3-10',
    title: '옹진군',
    main: '인천광역시',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-4-1',
    title: '춘천시',
    main: '강원도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-4-2',
    title: '원주시',
    main: '강원도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-4-3',
    title: '강릉시',
    main: '강원도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-4-4',
    title: '동해시',
    main: '강원도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-4-5',
    title: '태백시',
    main: '강원도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-4-6',
    title: '속초시',
    main: '강원도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-4-7',
    title: '삼척시',
    main: '강원도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-4-8',
    title: '홍천군',
    main: '강원도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-4-9',
    title: '횡성군',
    main: '강원도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-4-10',
    title: '영월군',
    main: '강원도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-4-11',
    title: '평창군',
    main: '강원도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-4-12',
    title: '정선군',
    main: '강원도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-4-13',
    title: '철원군',
    main: '강원도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-4-14',
    title: '화천군',
    main: '강원도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-4-15',
    title: '양구군',
    main: '강원도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-4-16',
    title: '인제군',
    main: '강원도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-4-17',
    title: '고성군',
    main: '강원도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-4-18',
    title: '양양군',
    main: '강원도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },

  {
    uid: '',
    id: 'KR-5-1',
    title: '청주시',
    main: '충청북도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-5-2',
    title: '충주시',
    main: '충청북도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-5-3',
    title: '제천시',
    main: '충청북도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-5-4',
    title: '보은군',
    main: '충청북도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-5-5',
    title: '옥천군',
    main: '충청북도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-5-6',
    title: '영동군',
    main: '충청북도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-5-7',
    title: '증평군',
    main: '충청북도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-5-8',
    title: '진천군',
    main: '충청북도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-5-9',
    title: '괴산군',
    main: '충청북도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-5-10',
    title: '음성군',
    main: '충청북도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-5-11',
    title: '단양군',
    main: '충청북도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },

  {
    uid: '',
    id: 'KR-6-1',
    title: '천안시',
    main: '충청남도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-6-2',
    title: '공주시',
    main: '충청남도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-6-3',
    title: '보령시',
    main: '충청남도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-6-4',
    title: '아산시',
    main: '충청남도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-6-5',
    title: '서산시',
    main: '충청남도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-6-6',
    title: '논산시',
    main: '충청남도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-6-7',
    title: '계룡시',
    main: '충청남도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-6-8',
    title: '당진시',
    main: '충청남도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-6-9',
    title: '금산군',
    main: '충청남도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-6-10',
    title: '부여군',
    main: '충청남도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-6-11',
    title: '서천군',
    main: '충청남도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-6-12',
    title: '청양군',
    main: '충청남도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-6-13',
    title: '홍성군',
    main: '충청남도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-6-14',
    title: '예산군',
    main: '충청남도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-6-15',
    title: '태안군',
    main: '충청남도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-7',
    title: '대전광역시',
    main: '대전광역시',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-8',
    title: '세종특별자치시',
    main: '세종특별자치시',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },

  {
    uid: '',
    id: 'KR-9-1',
    title: '전주시',
    main: '전라북도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-9-2',
    title: '군산시',
    main: '전라북도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-9-3',
    title: '익산시',
    main: '전라북도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-9-4',
    title: '정읍시',
    main: '전라북도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-9-5',
    title: '남원시',
    main: '전라북도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-9-6',
    title: '김제시',
    main: '전라북도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-9-7',
    title: '완주군',
    main: '전라북도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-9-8',
    title: '진안군',
    main: '전라북도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-9-9',
    title: '무주군',
    main: '전라북도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-9-10',
    title: '장수군',
    main: '전라북도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-9-11',
    title: '임실군',
    main: '전라북도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-9-12',
    title: '순창군',
    main: '전라북도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-9-13',
    title: '고창군',
    main: '전라북도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-9-14',
    title: '부안군',
    main: '전라북도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-10-1',
    title: '목포시',
    main: '전라남도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-10-2',
    title: '여수시',
    main: '전라남도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-10-3',
    title: '순천시',
    main: '전라남도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-10-4',
    title: '나주시',
    main: '전라남도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-10-5',
    title: '광양시',
    main: '전라남도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-10-6',
    title: '담양군',
    main: '전라남도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-10-7',
    title: '곡성군',
    main: '전라남도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-10-8',
    title: '구례군',
    main: '전라남도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-10-9',
    title: '고흥군',
    main: '전라남도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-10-10',
    title: '보성군',
    main: '전라남도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-10-11',
    title: '화순군',
    main: '전라남도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-10-12',
    title: '장흥군',
    main: '전라남도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-10-13',
    title: '강진군',
    main: '전라남도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-10-14',
    title: '해남군',
    main: '전라남도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-10-15',
    title: '영암군',
    main: '전라남도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-10-16',
    title: '무안군',
    main: '전라남도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-10-17',
    title: '함평군',
    main: '전라남도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-10-18',
    title: '영광군',
    main: '전라남도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-10-19',
    title: '장성군',
    main: '전라남도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-10-20',
    title: '완도군',
    main: '전라남도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-10-21',
    title: '진도군',
    main: '전라남도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-10-22',
    title: '신안군',
    main: '전라남도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-11',
    title: '광주광역시',
    main: '광주광역시',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-12-1',
    title: '포항시',
    main: '경상북도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-12-2',
    title: '경주시',
    main: '경상북도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-12-3',
    title: '김천시',
    main: '경상북도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-12-4',
    title: '안동시',
    main: '경상북도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-12-5',
    title: '구미시',
    main: '경상북도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-12-6',
    title: '영주시',
    main: '경상북도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-12-7',
    title: '영천시',
    main: '경상북도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-12-8',
    title: '상주시',
    main: '경상북도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-12-9',
    title: '문경시',
    main: '경상북도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-12-10',
    title: '경산시',
    main: '경상북도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-12-11',
    title: '군위군',
    main: '경상북도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-12-12',
    title: '의성군',
    main: '경상북도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-12-13',
    title: '청송군',
    main: '경상북도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-12-14',
    title: '영양군',
    main: '경상북도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-12-15',
    title: '영덕군',
    main: '경상북도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-12-16',
    title: '청도군',
    main: '경상북도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-12-17',
    title: '고령군',
    main: '경상북도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-12-18',
    title: '성주군',
    main: '경상북도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-12-19',
    title: '칠곡군',
    main: '경상북도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-12-20',
    title: '예천군',
    main: '경상북도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-12-21',
    title: '봉화군',
    main: '경상북도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-12-22',
    title: '울진군',
    main: '경상북도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-12-23',
    title: '울릉군',
    main: '경상북도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-13-1',
    title: '창원시',
    main: '경상남도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-13-2',
    title: '진주시',
    main: '경상남도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-13-3',
    title: '통영시',
    main: '경상남도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-13-4',
    title: '사천시',
    main: '경상남도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-13-5',
    title: '김해시',
    main: '경상남도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-13-6',
    title: '밀양시',
    main: '경상남도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-13-7',
    title: '거제시',
    main: '경상남도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-13-8',
    title: '양산시',
    main: '경상남도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-13-9',
    title: '의령군',
    main: '경상남도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-13-10',
    title: '함안군',
    main: '경상남도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-13-11',
    title: '창녕군',
    main: '경상남도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-13-12',
    title: '고성군',
    main: '경상남도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-13-13',
    title: '남해군',
    main: '경상남도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-13-14',
    title: '하동군',
    main: '경상남도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-13-15',
    title: '산청군',
    main: '경상남도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-13-16',
    title: '함양군',
    main: '경상남도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-13-17',
    title: '거창군',
    main: '경상남도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-13-18',
    title: '합천군',
    main: '경상남도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },

  {
    uid: '',
    id: 'KR-14',
    title: '부산광역시',
    main: '부산광역시',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-15',
    title: '대구광역시',
    main: '대구광역시',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-16',
    title: '울산광역시',
    main: '울산광역시',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
  {
    uid: '',
    id: 'KR-17',
    title: '제주특별자치도',
    main: '제주특별자치도',
    type: 'init',
    background: '#ffffff',
    story: 0,
  },
];

export const koreaRegionIdArray = Object.keys(koreaMapDataInit);
